---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: kopia-daily-maintenance
  namespace: volsync
spec:
  enabled: true
  moverVolumes:
    - mountPath: repository
      volumeSource:
        nfs:
          path: /volume2/Media/backup/volsync
          server: 10.0.0.123
  repository:
    repository: volsync-secret
  trigger:
    schedule: "30 3,15 * * *"
