---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.11.100:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.11.100"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "home-ops-0"
    ipAddress: "10.0.11.11"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4ae30c74e1f44a98bc448fabd92f7d1e4e1e85d06c9e720eb82ce1271963080e
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "88:ae:dd:67:83:24"
        dhcp: false
        addresses:
          - "10.0.11.11/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.0.11.1"
        mtu: 1500
        vip:
          ip: "10.0.11.100"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

